### ISSUE TITLE
Where is  latest openFrameworks (0.10.0)?

### ISSUE THREAD

**Issue by jinkeep** [HalfdanJ/ofxARCore#2]
Where is  latest openFrameworks (0.10.0)?
I can't find it.There is only 0.9.8 version 

Thanks

**Comment by HalfdanJ** [comment]
I've clarified it more in the README now. Its from github: https://github.com/openframeworks/openFrameworks/

**Comment by HalfdanJ** [comment]
I'm sorry. Releasing this addon went a bit to fast, I noticed I had some local modifications to openFrameworks that aren't in the official repo. I've made a PR for them, but in the meantime you will need my branch: https://github.com/halfdanj/openframeworks/tree/android-camera-permissions
