### ISSUE TITLE
i can not build apk using this source code

### ISSUE THREAD

**Issue by runningman8** [HalfdanJ/ofxARCore#4]
i can not build apk using this source code
can u build an apk and upload?

**Comment by bilazzokveton04** [comment]
Yes, a demo APK would be soo good

**Comment by ChengZhang1213** [comment]
I successfully built this project ,you can find the apk from this [url](https://github.com/ChengZhang1213/arcore_android_sdk_sample/tree/master/apk)
notice: when i compile this  project , i met the problem: ofxAndroidCheckCameraPermission() method can't find ,so when you use this apk,you must confirm the camera permission is opened.

**Comment by HalfdanJ** [comment]
Here is also a tutorial on how to use openFrameworks with Android: https://medium.com/energeia/getting-started-with-openframeworks-on-android-5202b92f6582

**Comment by bilazzokveton04** [comment]
Thank you both ChengZhang1213 and HalfdanJ!!!

I downloaded and install the apk, it works but it crashes as soon as I open it. How can I confirm the camera permission is opnened?

**Comment by ChengZhang1213** [comment]
@Cyber-Rabbit  if your android device  is Google Pixel, you can enter settings>Apps & notifications>App info, find the AR Drawing application ，the item which name is Permissions is what you want.I think you can compile this project successfully based on the tutorial given by HalfdanJ

**Comment by bilazzokveton04** [comment]
@ChengZhang1213 thank you very much for your help. The app is runing perfectly, I will be enjoying this now ::)
