### ISSUE TITLE
I cannot build the app using the code

### ISSUE THREAD

**Issue by bilazzokveton04** [HalfdanJ/ofxARCore#7]
Hello, 

Really appreciate that you wrote this code and shared with people. 

I have been trying the last couple of days but unfortunately I still havent been able to create this drawing app.

Any chance youd provide an APK file so we can try it?

**Comment by HalfdanJ** [comment]
Sorry, I can't share an apk, but try follow this openFrameworks tutorial to get started with openFrameworks: https://medium.com/energeia/getting-started-with-openframeworks-on-android-5202b92f6582
